Fix issue#109
bgo-bioimagerie/platformmanager pull request #207
Opened 2021-07-06 15:21 UTC by gaetanHerve

enhancement : booking invoices can be generated taking quantities into account
By default, even if quantity field is not displayed in booking edition form, quantity = 1
Shouldn't have any impact on cases when not using quantity parameter

2021-07-06 16:18 UTC, osallou commented on Modules/booking/Controller/BookinginvoiceController.php
> +                    $qte = $resaDayNightWe["res_quantity"];
not sure quantities should be multiplied by duration, should be checked to understand how it is expected to work

2021-09-07 11:47 UTC, osallou commented
waiting for customer review

2021-09-13 07:51 UTC, gaetanHerve commented
Customer review ok, but need to resolve functional conflicts with pfm2 branch

2021-09-27 12:49 UTC, gaetanHerve commented
For our information: testing this MR I had some problems linked to the fact that "is_invoicing_unit" column wasn't present in my bk_calquantities table. However I had a fresh db install and CoreInstall::upgrade_v1_v2 add the column (line 120):
```
$bkqte = new BkCalQuantities();
$bkqte->addColumn("bk_calquantities", "is_invoicing_unit", "int(1)", 0);
```

2021-09-28 13:38 UTC, osallou requested changes

2021-09-28 13:38 UTC, osallou commented on Framework/Email.php
> +    public function sendEmail($from, $fromName, $toAdress, $subject, $content, $sentCopyToFrom = false, $files = [], $bcc=true ) {
regressio toaddress => toadress

2021-09-28 13:38 UTC, osallou commented on Framework/Router.php
> -        $sendToSentry = true;
regression, removes pfmauth handling

2021-09-28 13:38 UTC, osallou commented on Modules/booking/Controller/BookingquantitiesController.php
> -            /* bug to get last id (could conflict)
regression, remove commented code and removes above corevirtual use

2021-09-28 13:38 UTC, osallou commented on Modules/booking/Controller/BookingschedulingController.php
> -                array($bkScheduling["is_monday"], $bkScheduling["is_tuesday"], $bkScheduling["is_wednesday"], $bkScheduling["is_thursday"], $bkScheduling["is_friday"], $bkScheduling["is_saturday"], $
regression on naming

2021-09-28 13:38 UTC, osallou commented on Modules/booking/Model/BkCalQuantities.php
> -        $sql = "select id from bk_calquantities where id_quantity=? AND id_resource=? AND deleted=0 AND id_space=?";
removes deleted=0

2021-09-28 13:38 UTC, osallou commented on Modules/booking/Model/BkScheduling.php
> -            "resa_time_setting" => 1, "default_color_id" => 1, "id_rearea" => 0);
removes rearea

2021-10-01 09:21 UTC, closed without merging