remove update from setprojectuser
bgo-bioimagerie/platformmanager pull request #665
Opened 2022-06-23 08:42 UTC by gaetanHerve

remove useless update from SeProject::setProjectUser()

2022-06-23 08:46 UTC, osallou requested changes
Si on appelle pls fois la fonction on va faire pls insert

2022-06-23 09:14 UTC, gaetanHerve commented on Modules/services/Model/SeProject.php
> +        $sql = "INSERT INTO se_project_user (id_space, id_user, id_project) VALUES (?, ?, ?)";
en effet, je devrais réfléchir parfois :)

2022-06-23 09:21 UTC, gaetanHerve commented on Modules/services/Model/SeProject.php
> +        $sql = "INSERT INTO se_project_user (id_space, id_user, id_project) VALUES (?, ?, ?)";
je suis passé trop vite sur cette mécanique. Cela n'a pas le comportement souhaité en bdd. Je n'avais pas vu d'effet de bdd en testant l'interface... je me penche dessus

2022-06-24 12:18 UTC, osallou approved these changes

2022-06-24 12:27 UTC, gaetanHerve commented on Modules/services/Controller/ServicesprojectsController.php
> +            $_SESSION['flash'] = $_SESSION['flash'] . " " . ServicesTranslator::projectEdited($lang);
ah oui, je peux rajouter le check dans le cas où il serait vide, ça sera plus propre, bien que PHP n'en ait cure manifestement. Au pire, $_SESSION['flash'] == null et le string est construit malgré tout.
Ici, cette ligne gère le cas où dans $this->updateProject(), on voit que l'utilisateur principal du projet a été supprimé de la liste des utilisateurs. Dans ce cas, je passe un message, spécifiant qu'il a été ajouté automatiquement, directement à $_SESSION['flash'] plutôt que de le faire retourner par la fonction, qui renvoie déjà l'id projet (ça serait pas très clair non plus).
Du coup je concatène les 2 strings dans $_SESSION['flash'] pour afficher les 2 messages à la validation du form...

Je rajoute le check et je repushe

2022-06-24 12:48 UTC, osallou commented on Modules/services/Controller/ServicesprojectsController.php
> +            $_SESSION['flash'] = $_SESSION['flash'] . " " . ServicesTranslator::projectEdited($lang);
Ok. Sur le principe, on pourrait gere un tableau ds flash, et ainsi en afficher pls dans la vue.

Ainsi on n aurait qu a ajouter des messages au besoin

A ameliorer plus tard

2022-06-27 14:08 UTC, osallou requested changes

2022-06-27 14:32 UTC, osallou approved these changes

2022-06-27 14:33 UTC, merged